version: '3.6'
services:
    qbittorrent:
        privileged: true
        build: qbittorrentvpn_mc
        container_name: qbit
        environment:
            - VPN_ENABLED=yes
            - VPN_USERNAME=#put your vpn creds here
            - VPN_PASSWORD=#and here
            - NAME_SERVERS=1.1.1.1,8.8.8.8
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - UMASK_SET=022
            - WEBUI_PORT=8080
            - LAN_NETWORK=192.168.0.0/24
        volumes:
            - ./config:/config
            - ./downloads:/downloads #chose where you want to store downloaded files
            - ./vuetorrent:/vuetorrent
        ports:
            - 8000:8080
        restart: unless-stopped
