version: '3.6'
services:
    qbittorrent:
        privileged: true
        image: dyonr/qbittorrentvpn
        container_name: qbit
        environment:
            - VPN_ENABLED=yes
            - VPN_TYPE=wireguard
            - NAME_SERVERS=1.1.1.1,8.8.8.8
            - TZ=Europe/Paris
            - UMASK_SET=022
            - LAN_NETWORK=192.168.0.0/24 #Set your lan network subnet
            - ENABLE_SSL=yes
        volumes:
            - ./config:/config
            - ./downloads:/downloads #chose where you want to store downloaded files
            - ./vuetorrent:/vuetorrent
        ports:
            - 8080:8080
        restart: unless-stopped
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
